#!/bin/bash
BATCH -J myjob          # Job name
SBATCH -o myjob.1.out   # define stdout filename; %j expands to jobid
SBATCH -e myjob.1.err   # define stderr filename; skip to combine stdout and stderr

#SBATCH --mail-user=bjones@tacc.utexas.edu
#SBATCH --mail-type=ALL
SBATCH -A cc5fpcp       # specify the project or allocation number

#SBATCH -p normal         # specify queue
#SBATCH -N 2              # Number of nodes, not cores (16 cores/node)
#SBATCH -n 32             # Total number of MPI tasks (if omitted, n=N)
#SBATCH -t 00:30:00       # set maximum run time of 30 minutes

#module load fftw3         # Load any necessary modules (these are examples)
mpirun ./*sh        # TACC systems use "ibrun", not "mpirun"
